version: "3.0"
services:
  postgres:
    image: postgres:latest
    env_file:
      - ".env"
    ports:
      - 127.0.0.1:5433:5432
  www:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    volumes:
      - ".:/app/:Z"
    ports:
      - 127.0.0.1:8080:8000